config/routes.rb
Rails.application.routes.draw do
  resources :rolls
  devise_for :admins
  devise_for :users
  get 'pages/info'
  get '/check/:id' => 'rolls#check'

  get 'ideas/my' => 'ideas#my' ,as: :my
  get 'ideas/sea' => 'ideas#sea' ,as: :sea
  get 'ideas/sd' => 'ideas#sd' ,as: :sd
  resources :ideas
  get "pages/info"

  authenticated :user do
    root :to => redirect('/ideas')
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
belongs_to :user
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def sea
    if current_user.admin?
      redirect_to rolls_path
      @ideas = Idea.all

      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        #@posts = User.all.order('created_at DESC')
      end

    else
      @ideas = Idea.all

      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        #@posts = User.all.order('created_at DESC')
      end
    end

  end

  def sd
    if current_user.admin?
      redirect_to rolls_path
      @ideas = Idea.all

      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        @posts = User.all.order('created_at DESC')
      end

    else

      @ideas = Idea.all
      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        @posts = User.all.order('created_at DESC')
      end
    end

  end
  def my
    if current_user.admin?
      redirect_to rolls_path
      @ideas = Idea.all

      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        @posts = User.all.order('created_at DESC')
      end

    else

      @ideas = Idea.all
      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        puts "****************************************************************"
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
        puts "****************************************************************"
      else
        puts "////////////////////////////////////////////////////////////////"
        @posts = User.all.order('created_at DESC')
        puts "////////////////////////////////////////////////////////////////"
      end
    end

  end
  def index
    if current_user.admin?
        redirect_to rolls_path
      @ideas = Idea.all

      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        #@posts = User.all.order('created_at DESC')
      end

    else
      @ideas = Idea.all

      @user =current_user
      @users =  User.all
      @posts = User.all
      if params[:search]
        @posts = User.search(params[:search]).order("created_at DESC")
        @posts.name
      else
        #@posts = User.all.order('created_at DESC')
      end
    end

  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
 def destroy
    if current_user == @idea.user
      @idea.destroy
    else
      redirect_to @idea, error: "You don't have permission."
    end
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => {:multipart => true} do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1><%= current_user.name %></h1>
<p><%= image_tag(@user.picture_url, :width => 100) if @user.picture.present? %></p>
<p><strong></strong><a><%= current_user.email %></strong></a>.</p>
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<p class="article-title">



<table class="table table-striped">

  <% @users.each_with_index do |user, index| %>

      <tr>
        <td><%= index +=1 %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                  "data-sid" => current_user.id, "data-rip" => user.id %>
              </td></br>
              </tr>

          <% end %>
          </table>






<br>

app/views/ideas/my.html.erb
<h1><%= current_user.name %></h1>
<p><%= image_tag(@user.picture_url, :width => 100) if @user.picture.present? %></p>
<p><strong></strong><a><%= current_user.email %></strong></a>.</p>
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<p class="article-title">

<h1>User Profile</h1>

<div class="pro-set">
  <h1>Name : </h1>  <h3 class="pro-h3"><%= current_user.name %> </h3>
  <h1>Father Name : </h1><h3 class="pro-h3"><%= current_user.fname %></h3>
  <h1>Email : </h1><h3 class="pro-h3"><%= current_user.email %> </h3>
  <h1>Contact : </h1><h3 class="pro-h3"><%= current_user.contact %></h3>
  <h1>Enrollment : </h1><h3 class="pro-h3"><%= current_user.enrollment %></h3>
  <h1> Session : </h1><h3 class="pro-h3"><%= current_user.session %></h3>
  <h1>Department : </h1><h3 class="pro-h3"><%= current_user.department %> </h3>
  <h1>Address : </h1><h3 class="pro-h3"><%= current_user.address %></h3>
  <h1>Work at : </h1><h3 class="pro-h3"><%= current_user.work_place %></h3>
  <h1> Work Experience : </h1><h3 class="pro-h3"><%= current_user.work_experience %></h3>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link btn btn-large btn-block btn-success' %>
</div>

<% if @posts.present? %>

    <h1>All Result Listed Here</h1>
    <% @posts.each do |article| %>
        <div class="article">
          <h1 class="article-title"><%= image_tag(article.picture_url, :width => 100) if article.picture.present? %><%= article.name %></h1>
          <p class="article-content"><%= article.email %><%= article.enrollment %><%= article.contact %></p>
          <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                  "data-sid" => current_user.id, "data-rip" => article.id %>
              </div>

          <%  end %>
          <% else %>

          </p>
          <% if (params[:search]) %>
              <h1>All Result Listed Here</h1>
              <p>There are no name in :db <%= params[:search] %>.</p>
          <% end %>
    <% end %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/sd.html.erb
<% if @posts.present? %>
    <h1>All Result Listed Here-my</h1>
    <% @posts.each do |article| %>
        <div class="article">
          <h1 class="article-title"><%= image_tag(article.picture_url, :width => 100) if article.picture.present? %><%= article.name %></h1>
          <p class="article-content"><%= article.email %><%= article.contact %></p>
          <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                  "data-sid" => current_user.id, "data-rip" => article.id %>
              </div>

          <%  end %>
          <% else %>

          </p>
          <% if (params[:search]) %>
              <h1>All Result Listed Here</h1>
              <p>There are no name in :db <%= params[:search] %>.</p>
          <% end %>
    <% end %>

app/views/ideas/sea.html.erb
<h1><%= current_user.name %></h1>
<p><%= image_tag(@user.picture_url, :width => 100) if @user.picture.present? %></p>
<p><strong></strong><a><%= current_user.email %></strong></a>.</p>
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<p class="article-title">





              <h1>ALL Posts</h1>

              <table class="table table-bordered">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Picture</th>
                  <th colspan="3"></th>
                </tr>
                </thead>

              <tbody>
                <% @ideas.each do |idea| %>
                    <tr>
                      <td><%= idea.name %></td>
                      <td><%= idea.description %></td>
                      <td><%= idea.picture %></td>
                      <td><%= link_to 'Show', idea %></td>
                      <% if idea.id == current_user.id %>
                      <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
                      <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      <% end %>
                    </tr>
                <% end %>
                </tbody>

              </table>

              <%= link_to 'New Idea', new_idea_path %>
              <br>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>