config/routes.rb
Rails.application.routes.draw do
  resources :rolls
  devise_for :admins
  devise_for :users
  get 'pages/info'
  get '/check/:id' => 'rolls#check'

  get 'ideas/my' => 'ideas#my' ,as: :my
  get 'ideas/sea' => 'ideas#sea' ,as: :sea
  get 'ideas/sd' => 'ideas#sd' ,as: :sd
  resources :ideas
  get "pages/info"

  authenticated :user do
    root :to => redirect('/ideas')
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/models/roll.rb
class Roll < ActiveRecord::Base
end

app/controllers/rolls_controller.rb
class RollsController < ApplicationController
  before_action :set_roll, only: [:show, :edit, :update, :destroy]

  # GET /rolls
  # GET /rolls.json

  def index
    @rolls = Roll.all
  end

  # GET /rolls/1
  # GET /rolls/1.json
  def show
  end

  # GET /rolls/new
  def new
    @roll = Roll.new
  end

  # GET /rolls/1/edit
  def edit
  end

  # POST /rolls
  # POST /rolls.json
  def create
    @roll = Roll.new(roll_params)

    respond_to do |format|
      if @roll.save
        format.html { redirect_to @roll, notice: 'Roll was successfully created.' }
        format.json { render :show, status: :created, location: @roll }
      else
        format.html { render :new }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rolls/1
  # PATCH/PUT /rolls/1.json
  def update
    respond_to do |format|
      if @roll.update(roll_params)
        format.html { redirect_to @roll, notice: 'Roll was successfully updated.' }
        format.json { render :show, status: :ok, location: @roll }
      else
        format.html { render :edit }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  def check
    @roll = Roll.find(params[:id])
    if(@roll.present?)
     printf(" <h1>yoyo</h1>")
    else
      printf(" yoyo")
    end
  end

  # DELETE /rolls/1
  # DELETE /rolls/1.json
  def destroy
    @roll.destroy
    respond_to do |format|
      format.html { redirect_to rolls_url, notice: 'Roll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roll
      @roll = Roll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roll_params
      params.require(:roll).permit(:enroll)
    end
end

app/helpers/rolls_helper.rb
module RollsHelper
end

app/views/rolls/_form.html.erb
<%= form_for(@roll) do |f| %>
  <% if @roll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roll.errors.count, "error") %> prohibited this roll from being saved:</h2>

      <ul>
      <% @roll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enrollment_id %><br>
    <%= f.text_field :enroll %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rolls/edit.html.erb
<h1>Editing Roll</h1>

<%= render 'form' %>

<%= link_to 'Show', @roll, class:"btn btn-info" %> |
<%= link_to 'Back', rolls_path, class:"btn btn-info" %>

app/views/rolls/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Admin Panel</h1><br>
<h1>All ENROLLMENT ID's</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Enrollment Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rolls.each do |roll| %>
      <tr>
        <td><%= roll.enroll %></td>
        <td><%= link_to 'Show', roll, class:"btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_roll_path(roll), class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', roll, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roll', new_roll_path , class:"btn btn-success" %>

app/views/rolls/new.html.erb
<h1>New Roll</h1>

<%= render 'form' %>

<%= link_to 'Back', rolls_path, class:"btn btn-info" %>

app/views/rolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Enroll:</strong>
  <%= @roll.enroll %>
</p>

<%= link_to 'Edit', edit_roll_path(@roll), class:"btn btn-info" %> |
<%= link_to 'Back', rolls_path, class:"btn btn-info" %>