config/routes.rb
Rails.application.routes.draw do
  resources :rolls
  devise_for :admins
  devise_for :users
  get 'pages/info'
  get '/check/:id' => 'rolls#check'

  get 'ideas/my' => 'ideas#my' ,as: :my
  get 'ideas/sea' => 'ideas#sea' ,as: :sea
  get 'ideas/sd' => 'ideas#sd' ,as: :sd
  resources :ideas
  get "pages/info"

  authenticated :user do
    root :to => redirect('/ideas')
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ALUMNI CONNECT</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= csrf_meta_tags %>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ALUMNI CONNECT</a>
    </div>
    <div class="collapse navbar-collapse">
      <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li class="active"><a href="/ideas/my">Profile</a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="active"><a href="/ideas/sea">Post</a></li>
          </ul>
          <ul class="nav navbar-nav">
            <li class="active"><%= form_tag(sd_path, :method => "get", id: "show") do %></li>
            <li class="active"><%= text_field_tag :search, params[:search], placeholder: "Search Posts" %></li>
            <li class="active"><%= submit_tag "Search" %></li>
              </ul>
      <% end %>
      <% else %>
          <% if admin_signed_in? %>
              <ul class="nav navbar-nav">
                <li class="active"><a href="/ideas/my">Profile</a></li>
              </ul>
              <ul class="nav navbar-nav">
                <li class="active"><a href="/ideas/sea">Post</a></li>
              </ul>
          <% end %>
          <% if !admin_signed_in? %>

          <% end %>
      <% end %>

      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
            <% if admin_signed_in? %>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% end %>
            <% if !admin_signed_in? %>
                 <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
        <% end %>



        </div>
  </div>
</nav>
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    FINAL PROJECT.
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
<audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>
</body>
</html>